#!/usr/bin/env bash

# Builds the addon jar. Needs JDK 17+ and the mod jars in libs/.
# create-fabric-0_5_1-j-build_1631_mc1_20_1.jar
# Steam_Rails-1_6_9_fabric-mc1_20_1.jar
# fabric-api-0.92.7+1.20.1.jar
# fabric-loader-0.16.3.jar

set -euo pipefail

cd "$(dirname "$0")"

# Mod parameters (baked into the JAR).

# top height in px above straight casing or slab (0 = flush, higher = higher)
HEIGHT="${HEIGHT:-0.003}"

# height offset of the main pieces above the lower (gap-filling) pieces, in blocks (anti-z-fighting)
SECONDARY_LAYER="${SECONDARY_LAYER:-0.005}"
# extra height offset between consecutive main pieces, in blocks (anti-z-fighting)
LAYER="${LAYER:-0.0025}"

# width and length scale of the lower (gap-filling) pieces around their center; 1 = full size, 0.95 = slightly smaller
SECONDARY_SCALE="${SECONDARY_SCALE:-0.99}"

# rotation of the lower (gap-filling) pieces around the vertical axis through their center, in degrees (decimals ok, positive = clockwise from above)
SECONDARY_ROTATION="${SECONDARY_ROTATION:-0.9}"
# rotation of the main pieces around the vertical axis through their center, in degrees (decimals ok, positive = clockwise from above)
ROTATION="${ROTATION:-0.8}"

# mod version; empty = use fabric.mod.json (VERSION= ./build.sh)
VERSION="${VERSION-1.1.0}"

# Accepts decimals (also with a comma); fails early on anything that is not a number.
num() {
    local v="${1//,/.}"
    [[ "$v" =~ ^-?([0-9]+\.?[0-9]*|\.[0-9]+)$ ]] || { echo "$2 must be a number, got '$1'" >&2; exit 1; }
    printf '%s' "$v"
}
for name in HEIGHT SECONDARY_LAYER LAYER SECONDARY_SCALE SECONDARY_ROTATION ROTATION; do
    value=$(num "${!name}" "$name") || exit 1
    printf -v "$name" '%s' "$value"
done

SR=$(find libs -maxdepth 1 -name 'Steam_Rails*.jar' -print -quit)
CR=$(find libs -maxdepth 1 -name 'create-fabric*.jar' -print -quit)
FA=$(find libs -maxdepth 1 -name 'fabric-api*.jar' -print -quit)
FL=$(find libs -maxdepth 1 -name 'fabric-loader*.jar' -print -quit)

if [ -z "$SR" ] || [ -z "$CR" ] || [ -z "$FA" ] || [ -z "$FL" ]; then
    echo "put Steam_Rails-*.jar, create-fabric-*.jar, fabric-api*.jar and fabric-loader*.jar into libs/" >&2
    exit 1
fi

VER="$VERSION"
[ -n "$VER" ] || VER=$(sed -n 's/.*"version": *"\([^"]*\)".*/\1/p' \
    src/main/resources/fabric.mod.json | head -1)

rm -rf build
mkdir -p build/nested build/classes build/res build/gen/io/github/rebootless/curvefix

cp -r src/main/resources/. build/res/
sed -i "s/\(\"version\": *\"\)[^\"]*/\1$VER/" build/res/fabric.mod.json

cat > build/gen/io/github/rebootless/curvefix/Tunables.java <<EOF
package io.github.rebootless.curvefix;

/** Generated by build.sh. */
final class Tunables {
    private Tunables() {}
    static final float HEIGHT_PX = ${HEIGHT}f;
    static final float SECONDARY_SCALE = ${SECONDARY_SCALE}f;
    static final float SECONDARY_ROTATION_DEG = ${SECONDARY_ROTATION}f;
    static final float ROTATION_DEG = ${ROTATION}f;
    static final float SECONDARY_LAYER = ${SECONDARY_LAYER}f;
    static final float LAYER = ${LAYER}f;
}
EOF

unzip -q -o "$CR" 'META-INF/jars/*.jar' -d build/nested

NESTED_CP=$(find build/nested/META-INF/jars \
    -name '*.jar' -print0 | tr '\0' ':')

CP="$FL:$FA:$SR:$CR:$NESTED_CP"

javac --release 17 \
    -proc:none \
    -Xlint:none \
    -cp "$CP" \
    -sourcepath stubs \
    -d build/classes \
    $(find src/main/java build/gen -name '*.java')

OUT="build/railways-curvefix-$VER.jar"

jar --create \
    --file "$OUT" \
    -C build/classes io \
    -C build/res .

echo "built $OUT"
